// Code generated by gotmpl. DO NOT MODIFY.
// source: internal/shared/semconv/util.go.tmpl

// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package semconv // import "go.opentelemetry.io/contrib/instrumentation/github.com/gorilla/mux/otelmux/internal/semconv"

import (
	"net/http"
	"time"

	"go.opentelemetry.io/otel/attribute"
	semconvNew "go.opentelemetry.io/otel/semconv/v1.41.0"
)

// SplitHostPort splits a network address hostport of the form "host",
// "host%zone", "[host]", "[host%zone], "host:port", "host%zone:port",
// "[host]:port", "[host%zone]:port", or ":port" into host or host%zone and
// port.
//
// An empty host is returned if it is not provided or unparsable. A negative
// port is returned if it is not provided or unparsable.
func SplitHostPort(hostport string) (host string, port int) {
	_ = "STUB: not implemented"
	return "", 0
}

// Invalid hostport.

//nolint:gosec  // Byte size checked 16 above.

func requiredHTTPPort(https bool, port int) int {
	_ = "STUB: not implemented" //nolint:revive // ignore linter
	return 0
}

func serverClientIP(xForwardedFor string) string { _ = "STUB: not implemented"; return "" }

func httpRoute(pattern string) string { _ = "STUB: not implemented"; return "" }

func netProtocol(proto string) (name string, version string) {
	_ = "STUB: not implemented"
	return "", ""
}

var methodLookup = map[string]attribute.KeyValue{
	http.MethodConnect: semconvNew.HTTPRequestMethodConnect,
	http.MethodDelete:  semconvNew.HTTPRequestMethodDelete,
	http.MethodGet:     semconvNew.HTTPRequestMethodGet,
	http.MethodHead:    semconvNew.HTTPRequestMethodHead,
	http.MethodOptions: semconvNew.HTTPRequestMethodOptions,
	http.MethodPatch:   semconvNew.HTTPRequestMethodPatch,
	http.MethodPost:    semconvNew.HTTPRequestMethodPost,
	http.MethodPut:     semconvNew.HTTPRequestMethodPut,
	http.MethodTrace:   semconvNew.HTTPRequestMethodTrace,
}

func handleErr(err error) { _ = "STUB: not implemented"; return }

func standardizeHTTPMethod(method string) string { _ = "STUB: not implemented"; return "" }

func durationToSeconds(d time.Duration) float64 {
	_ = "STUB: not implemented"
	// Use floating point division here for higher precision (instead of Seconds method).
	return 0
}
