// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: hello-service.proto

package api

import (
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() { _ = "STUB: not implemented"; return }

func (x *HelloRequest) String() string { _ = "STUB: not implemented"; return "" }

func (*HelloRequest) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *HelloRequest) GetGreeting() string { _ = "STUB: not implemented"; return "" }

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reply         string                 `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() { _ = "STUB: not implemented"; return }

func (x *HelloResponse) String() string { _ = "STUB: not implemented"; return "" }

func (*HelloResponse) ProtoMessage() { _ = "STUB: not implemented"; return }

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	_ = "STUB: not implemented"
	return *new(protoreflect.Message)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) { _ = "STUB: not implemented"; return nil, nil }

func (x *HelloResponse) GetReply() string { _ = "STUB: not implemented"; return "" }

var File_hello_service_proto protoreflect.FileDescriptor

const file_hello_service_proto_rawDesc = "" +
	"\n" +
	"\x13hello-service.proto\x12\x03api\"*\n" +
	"\fHelloRequest\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting\"%\n" +
	"\rHelloResponse\x12\x14\n" +
	"\x05reply\x18\x01 \x01(\tR\x05reply2\x84\x02\n" +
	"\fHelloService\x121\n" +
	"\bSayHello\x12\x11.api.HelloRequest\x1a\x12.api.HelloResponse\x12?\n" +
	"\x14SayHelloServerStream\x12\x11.api.HelloRequest\x1a\x12.api.HelloResponse0\x01\x12?\n" +
	"\x14SayHelloClientStream\x12\x11.api.HelloRequest\x1a\x12.api.HelloResponse(\x01\x12?\n" +
	"\x12SayHelloBidiStream\x12\x11.api.HelloRequest\x1a\x12.api.HelloResponse(\x010\x01BYZWgo.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc/example/apib\x06proto3"

var (
	file_hello_service_proto_rawDescOnce sync.Once
	file_hello_service_proto_rawDescData []byte
)

func file_hello_service_proto_rawDescGZIP() []byte { _ = "STUB: not implemented"; return nil }

var file_hello_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hello_service_proto_goTypes = []any{
	(*HelloRequest)(nil),  // 0: api.HelloRequest
	(*HelloResponse)(nil), // 1: api.HelloResponse
}
var file_hello_service_proto_depIdxs = []int32{
	0, // 0: api.HelloService.SayHello:input_type -> api.HelloRequest
	0, // 1: api.HelloService.SayHelloServerStream:input_type -> api.HelloRequest
	0, // 2: api.HelloService.SayHelloClientStream:input_type -> api.HelloRequest
	0, // 3: api.HelloService.SayHelloBidiStream:input_type -> api.HelloRequest
	1, // 4: api.HelloService.SayHello:output_type -> api.HelloResponse
	1, // 5: api.HelloService.SayHelloServerStream:output_type -> api.HelloResponse
	1, // 6: api.HelloService.SayHelloClientStream:output_type -> api.HelloResponse
	1, // 7: api.HelloService.SayHelloBidiStream:output_type -> api.HelloResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init()                          { file_hello_service_proto_init() }
func file_hello_service_proto_init() { _ = "STUB: not implemented"; return }
