// Code generated by gotmpl. DO NOT MODIFY.
// source: internal/shared/semconv/client.go.tmpl

// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

// Package semconv provides OpenTelemetry semantic convention types and
// functionality.
package semconv // import "go.opentelemetry.io/contrib/instrumentation/github.com/labstack/echo/otelecho/internal/semconv"

import (
	"context"
	"net/http"

	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/semconv/v1.41.0/httpconv"
)

type HTTPClient struct {
	requestBodySize httpconv.ClientRequestBodySize
	requestDuration httpconv.ClientRequestDuration
}

func NewHTTPClient(meter metric.Meter) HTTPClient {
	_ = "STUB: not implemented"
	return *new(HTTPClient)
}

func (n HTTPClient) Status(code int) (codes.Code, string) {
	_ = "STUB: not implemented"
	return *new(codes.Code), ""
}

// RequestTraceAttrs returns trace attributes for an HTTP request made by a client.
func (n HTTPClient) RequestTraceAttrs(req *http.Request) []attribute.KeyValue {
	_ = "STUB: not implemented"
	/*
	 below attributes are returned:
	 - http.request.method
	 - http.request.method.original
	 - url.full
	 - server.address
	 - server.port
	 - network.protocol.name
	 - network.protocol.version
	*/return nil
}

// URL, server address, proto, and method.

// Remove any username/password info that may be in the URL.

// Restore any username/password info that was removed.

// ResponseTraceAttrs returns trace attributes for an HTTP response made by a client.
func (n HTTPClient) ResponseTraceAttrs(resp *http.Response) []attribute.KeyValue {
	_ = "STUB: not implemented"
	/*
	 below attributes are returned:
	 - http.response.status_code
	 - error.type
	*/return nil
}

func (n HTTPClient) method(method string) (attribute.KeyValue, attribute.KeyValue) {
	_ = "STUB: not implemented"
	return *new(attribute.KeyValue), *new(attribute.KeyValue)
}

func (n HTTPClient) MetricAttributes(req *http.Request, statusCode int, additionalAttributes []attribute.KeyValue) []attribute.KeyValue {
	_ = "STUB: not implemented"
	return nil
}

type MetricOpts struct {
	measurement metric.MeasurementOption
	addOptions  metric.AddOption
}

func (o MetricOpts) MeasurementOption() metric.MeasurementOption {
	_ = "STUB: not implemented"
	return *new(metric.MeasurementOption)
}

func (o MetricOpts) AddOptions() metric.AddOption {
	_ = "STUB: not implemented"
	return *new(metric.AddOption)
}

func (n HTTPClient) MetricOptions(ma MetricAttributes) MetricOpts {
	_ = "STUB: not implemented"
	return *new(MetricOpts)
}

// ErrorType returns an error.type attribute for the given error. The otelhttp
// Transport calls the underlying RoundTripper directly, so transport failures
// arrive as *net.OpError (connection refused, timeout, etc.) rather than
// *url.Error (which http.Client.Do adds above the Transport layer). This
// function intentionally does not unwrap further: reporting a single concrete
// type per failure keeps attribute cardinality bounded, as required by the
// OTel spec (error.type SHOULD have low cardinality). Callers that need
// finer-grained error distinctions should inspect the error themselves.
func (n HTTPClient) ErrorType(err error) attribute.KeyValue {
	_ = "STUB: not implemented"
	return *new(attribute.KeyValue)
}

// t.PkgPath() == "" covers builtin and unnamed types.
// t.Name() == "" covers anonymous struct types that implement error,
// which are uncommon but possible. Fall back to t.String() for both.

func (n HTTPClient) RecordMetrics(ctx context.Context, md MetricData, opts MetricOpts) {
	_ = "STUB: not implemented"
	return
}

// TraceAttributes returns attributes for httptrace.
func (n HTTPClient) TraceAttributes(host string) []attribute.KeyValue {
	_ = "STUB: not implemented"
	return nil
}

func (n HTTPClient) scheme(req *http.Request) attribute.KeyValue {
	_ = "STUB: not implemented"
	return *new(attribute.KeyValue)
}

func isErrorStatusCode(code int) bool { _ = "STUB: not implemented"; return false }
